version: '3'

volumes:
  pg_volume:
  static:
  media_volume:

services:
  postgres_db:
    image: postgres:13
    volumes:
      - pg_volume:/var/lib/postgresql/data
    env_file: .env  
  backend:
    image: fill9214/kittygram_backend
    env_file: .env
    volumes:
      - static:/backend_static
      - media_volume:/media
  frontend:
    env_file: .env
    image: fill9214/kittygram_frontend
    command: cp -r /app/build/. /static/
    volumes:
      - static:/frontend_static
  gateway:
    image: fill9214/kittygram_gateway
    env_file: .env
    ports:
      - 9000:80
    volumes:
      - static:/staticfiles/
      - media_volume:/media